"""A2q mutant list — `AccessibleTrader.Core/Services/Accessibility`.

Each entry: (id, area, file, find, replace, why the blind user notices).
Anchors were re-derived from the source at 87a4c257 (the survey's line numbers predate it).
Every anchor is asserted to occur EXACTLY ONCE before it is applied.

Weighting: the survey's ranked list (§3), the channel moves the 2026-09-30 F2 decision made
possible, and the never-mutated files (NavigationEngine, ViewportManager, SeriesNavigationRegistry,
NotificationHub, HistoryBufferCoordinator, HeadlessChart, HeadlessChartFactory, IndicatorContext
Analyzer, SdkCandlePatternAnalyzer, TablistNavigator, PointNavigationStrategy). The survey's dead
code (SpeakPoint/SpeakProfile/SpeakHeatmap, ViewportManager.GetRichViewportDescription/
AnnounceViewport/EnsureVisible, RecordEditForUndo, ICA NarrativeHint/TrendBars/band zones) is NOT
mutated.
"""

A = "AccessibleTrader.Core/Services/Accessibility/"
AFC = A + "AccessibilityFeedbackCoordinator.cs"

MUTANTS = [
    # ── Channel moves (the 2026-09-30 F2 decision) — call sites, not the router table ──────────
    ("C01", "new-bar sentence back on Event (Shift+F2) instead of Narration (F2)", AFC,
     "                _speechRouter.Speak(sentence, interrupt: false, channel: SpeechChannel.Narration);\n\n            // Reset intra-bar debounce",
     "                _speechRouter.Speak(sentence, interrupt: false, channel: SpeechChannel.Event);\n\n            // Reset intra-bar debounce",
     "F2 no longer silences new-bar announcements and Shift+F2 does — the decision reversed"),
    ("C02", "bar-close narration utterance on Event instead of Narration",
     A + "AutoNarrationService.cs",
     "_speechRouter.Speak(whole, interrupt: false, channel: SpeechChannel.Narration);",
     "_speechRouter.Speak(whole, interrupt: false, channel: SpeechChannel.Event);",
     "signals on bar close keep talking under F2 and are muted by Shift+F2"),
    ("C03", "forming candle commentary on Event instead of Narration", AFC,
     "                    _speechRouter.Speak(msg, interrupt: false, channel: SpeechChannel.Narration);",
     "                    _speechRouter.Speak(msg, interrupt: false, channel: SpeechChannel.Event);",
     "'forming hammer' commentary talks through F2"),
    ("C04", "forming chart formation on Chart (loses narration priority)", AFC,
     "            _speechRouter.Speak(sentence, interrupt: false, channel: SpeechChannel.Narration);\n            return true;",
     "            _speechRouter.Speak(sentence, interrupt: false, channel: SpeechChannel.Chart);\n            return true;",
     "the next arrow key cuts a forming double-top sentence off mid-word"),
    ("C05", "an ordinary price alert spoken on Chart (F2) instead of Event", AFC,
     "channel: pierce ? SpeechChannel.Critical : SpeechChannel.Event);",
     "channel: pierce ? SpeechChannel.Critical : SpeechChannel.Chart);",
     "muting chart navigation with F2 also silences every price alert"),
    ("C06", "'Chart speech off' confirmation on Chart — muted by itself", AFC,
     "\"Chart speech on\" : \"Chart speech off\",\n                    interrupt: true, channel: SpeechChannel.Critical);",
     "\"Chart speech on\" : \"Chart speech off\",\n                    interrupt: true, channel: SpeechChannel.Chart);",
     "pressing F2 is answered by silence: the user cannot tell muted from a dead key"),
    ("C07", "'Alerts and events muted' confirmation on Event — muted by itself", AFC,
     "\"Alerts and events on\" : \"Alerts and events muted\",\n                    interrupt: true, channel: SpeechChannel.Critical);",
     "\"Alerts and events on\" : \"Alerts and events muted\",\n                    interrupt: true, channel: SpeechChannel.Event);",
     "Shift+F2 is answered by silence"),
    ("C08", "'chart failed to load' on Chart", AFC,
     "_speechRouter.Speak(failMsg, interrupt: true, channel: SpeechChannel.Critical);",
     "_speechRouter.Speak(failMsg, interrupt: true, channel: SpeechChannel.Chart);",
     "with F2 on, a chart that fails to load says nothing"),
    ("C09", "'Removed X' confirmation on Chart instead of Interface",
     A + "NavigationEngine.cs",
     "$\"Removed {s.Name}\", Channel: SpeechChannel.Interface));",
     "$\"Removed {s.Name}\"));",
     "Delete on a series under F2 removes it silently"),
    ("C10", "margin/liquidation warning on Event (Shift+F2) instead of OrderEvent", AFC,
     "_speechRouter.Speak(e.Message, interrupt: true, channel: SpeechChannel.OrderEvent);",
     "_speechRouter.Speak(e.Message, interrupt: true, channel: SpeechChannel.Event);",
     "Shift+F2 mutes the warning that a leveraged position is near liquidation"),
    ("C11", "strategy order success back on the default Chart channel",
     A + "GlobalErrorCoordinator.cs",
     "IncludeSonification: true, Channel: SpeechChannel.OrderEvent));",
     "IncludeSonification: true));",
     "with F2 on, a strategy's order is announced only if it FAILS"),
    ("C12", "connection-lost retry published as Info (chart channel) not Alert",
     A + "GlobalErrorCoordinator.cs",
     "_eventBus.Publish(new FeedbackRequestEvent(FeedbackType.Alert, msg, true, IsUserInitiated: false));",
     "_eventBus.Publish(new FeedbackRequestEvent(FeedbackType.Info, msg, true, IsUserInitiated: false));",
     "F2 silences 'Connection lost'; the alert earcon is gone too"),
    ("C13", "'Braille off.' confirmation on Chart",
     A + "TactileCanvasCoordinator.cs",
     "_speech.Speak(enable ? \"Braille on.\" : \"Braille off.\",\n                    interrupt: true, channel: SpeechChannel.Critical);",
     "_speech.Speak(enable ? \"Braille on.\" : \"Braille off.\",\n                    interrupt: true, channel: SpeechChannel.Chart);",
     "F4 under F2 toggles braille with no confirmation"),
    ("C14", "Dot Pad connect/disconnect on Chart instead of Event",
     A + "TactileCanvasCoordinator.cs",
     "                channel: SpeechChannel.Event,\n                    interrupt: false);",
     "                channel: SpeechChannel.Chart,\n                    interrupt: false);",
     "F2 silences 'Dot Pad disconnected'"),
    ("C15", "NotificationHub advisory pierces Shift+F2 (Event→Critical)",
     A + "NotificationHub.cs",
     "        public void NotifyInfo(string message, bool interrupt = true)\n        {\n            _speechRouter.Speak(message, interrupt, SpeechChannel.Event);",
     "        public void NotifyInfo(string message, bool interrupt = true)\n        {\n            _speechRouter.Speak(message, interrupt, SpeechChannel.Critical);",
     "an indicator-parameter advisory talks through Shift+F2"),
    ("C16", "NotificationHub error muted by Shift+F2 (Critical→Event)",
     A + "NotificationHub.cs",
     "_speechRouter.Speak(message, interrupt, SpeechChannel.Critical);",
     "_speechRouter.Speak(message, interrupt, SpeechChannel.Event);",
     "an error is silent with Shift+F2 on"),

    # ── AccessibilityFeedbackCoordinator: alerts ─────────────────────────────────────────────
    ("A01", "speech-only alerts are silent", AFC,
     "if (alert.Definition.Delivery == AlertDelivery.Speech || alert.Definition.Delivery == AlertDelivery.Both)",
     "if (alert.Definition.Delivery == AlertDelivery.Both)",
     "a price alert set to Speech says nothing"),
    ("A02", "break-through alert no longer pierces (always Event)", AFC,
     "channel: pierce ? SpeechChannel.Critical : SpeechChannel.Event);",
     "channel: SpeechChannel.Event);",
     "Shift+F2 mutes an alert the user marked break-through"),
    ("A03", "break-through alert's earcon obeys the earcon mute", AFC,
     "_earconService.PlayAlert(breakThroughMutes: pierce);",
     "_earconService.PlayAlert(breakThroughMutes: false);",
     "a break-through alert's sound is muted by Shift+F3"),

    # ── AccessibilityFeedbackCoordinator: forming-pattern commentary ─────────────────────────
    ("A04", "forming-pattern debounce deleted", AFC,
     "            if (DateTime.UtcNow - _lastPatternAnnouncement < PatternDebounce) return;\n",
     "",
     "pattern commentary chatters on every tick a shape flips"),
    ("A05", "forming commentary without the candles' N flag", AFC,
     "if (candleSeries == null || !candleSeries.IsAutoNarrated) return;",
     "if (candleSeries == null) return;",
     "running commentary the user never switched on with N"),
    ("A06", "forming candle pattern repeated (change gate dropped)", AFC,
     "if (patternChanged && isInteresting)",
     "if (isInteresting)",
     "'forming hammer' every five seconds while it stays a hammer"),
    ("A07", "forming formation re-announced (identity memory ignored)", AFC,
     "            if (_lastFormingPattern == candidate.Identity) return false;\n",
     "",
     "the same forming double top is announced again and again"),
    ("A08", "forming commentary during playback", AFC,
     "            if (state.IsPlaying) return;\n",
     "",
     "pattern commentary talks over playback"),

    # ── AccessibilityFeedbackCoordinator: confirmations / status ─────────────────────────────
    ("A09", "Sound on/off confirmation inverted", AFC,
     "state.IsSonificationEnabled ? \"Sound on\" : \"Sound off\"",
     "state.IsSonificationEnabled ? \"Sound off\" : \"Sound on\"",
     "F3 says the opposite of what it did"),
    ("A10", "log/linear scale confirmation inverted", AFC,
     "state.IsLogScale ? \"Log scale\" : \"Linear scale\"",
     "state.IsLogScale ? \"Linear scale\" : \"Log scale\"",
     "the scale toggle names the wrong scale"),
    ("A11", "Heikin-Ashi/standard confirmation inverted", AFC,
     "                    : \"Standard candles\";",
     "                    : \"Heikin-Ashi candles\";",
     "turning Heikin-Ashi OFF says 'Heikin-Ashi candles'"),
    ("A12", "overlap count off by one", AFC,
     "$\" Plus {total - 1} more formation",
     "$\" Plus {total} more formation",
     "'plus 2 more formations' when there is one"),
    ("A13", "'Loading history...' deleted", AFC,
     "                _speechRouter.Speak(\"Loading history...\", true);\n",
     "",
     "a history load is silent; the chart seems frozen"),
    ("A14", "panning-step announcement deleted", AFC,
     "                _speechRouter.Speak($\"Panning step: {state.PanningGranularity} percent\");\n",
     "",
     "granularity keys say nothing"),

    # ── NavigationEngine (no direct test) ────────────────────────────────────────────────────
    ("N01", "no boundary earcon at the chart's left/right edge", A + "NavigationEngine.cs",
     "                // At data boundary: play earcon only — no spoken phrase per user preference.\n                _eventBus.Publish(new FeedbackRequestEvent(FeedbackType.Boundary, null, false));\n",
     "",
     "silence at the edge: indistinguishable from a dead key"),
    ("N02", "history backfill requested walking RIGHT", A + "NavigationEngine.cs",
     "if (delta < 0 && state.CurrentDataIndex < HistoryBackfillThreshold)",
     "if (delta > 0 && state.CurrentDataIndex < HistoryBackfillThreshold)",
     "walking left to the start never loads older history"),
    ("N03", "Page Up/Down wraps instead of clamping", A + "NavigationEngine.cs",
     "int newIndex = Math.Clamp(currentIndex + delta, 0, all.Count - 1);",
     "int newIndex = (currentIndex + delta + all.Count) % all.Count;",
     "Page Down on the last series teleports to the candles"),
    ("N04", "Delete may remove the candles", A + "NavigationEngine.cs",
     "if (!string.IsNullOrEmpty(id) && id != \"candles\")",
     "if (!string.IsNullOrEmpty(id))",
     "the price series can be deleted"),
    ("N05", "series switch keeps the stale component index", A + "NavigationEngine.cs",
     "                _store.Dispatch(new SelectComponentAction(0));\n",
     "",
     "Up/Down on the new series starts from a component of the old one"),
    ("N06", "Home jumps to bar 0, not the viewport's first bar", A + "NavigationEngine.cs",
     "_store.Dispatch(new SetCursorAction(state.ViewportStartIndex));",
     "_store.Dispatch(new SetCursorAction(0));",
     "Home lands off-screen"),
    ("N07", "no boundary earcon on Up/Down at the last component", A + "NavigationEngine.cs",
     "                // from \"the key is not working\".\n                _eventBus.Publish(new FeedbackRequestEvent(FeedbackType.Boundary, null, false));\n",
     "                // from \"the key is not working\".\n",
     "Up at the top component is silence"),
    ("N08", "granularity up decreases", A + "NavigationEngine.cs",
     "_store.Dispatch(new AdjustGranularityAction(5));",
     "_store.Dispatch(new AdjustGranularityAction(-5));",
     "the granularity-up key makes panning finer"),

    # ── ViewportManager / SeriesNavigationRegistry / PointNavigationStrategy ─────────────────
    ("V01", "pan direction reversed", A + "ViewportManager.cs",
     "_store.Dispatch(new WorkspacePanEvent(direction));",
     "_store.Dispatch(new WorkspacePanEvent(-direction));",
     "pan left moves the chart right"),
    ("V02", "pan backfill requested when panning right", A + "ViewportManager.cs",
     "if (direction < 0 && state.ViewportStartIndex < HistoryBackfillThreshold)",
     "if (direction > 0 && state.ViewportStartIndex < HistoryBackfillThreshold)",
     "panning to the start never loads older history"),
    ("R01", "a volume profile navigated as points", A + "SeriesNavigationRegistry.cs",
     "bool isBinned = series.IsProfile || series.Components.Any(",
     "bool isBinned = series.Components.Any(",
     "Up/Down on a profile walks components instead of price bins"),
    ("R02", "a heatmap navigated as points", A + "SeriesNavigationRegistry.cs",
     "bool isBinned = series.IsProfile || series.Components.Any(c => c.DisplayType == ComponentDisplayType.Heatmap);",
     "bool isBinned = series.IsProfile;",
     "Up/Down on a heatmap walks components instead of bins"),
    ("PN1", "Up at the top component reports success", A + "PointNavigationStrategy.cs",
     "            if (newComp == state.FocusedComponentIndex) return new NavigationResult(false);\n",
     "",
     "the component is re-read instead of the boundary earcon"),

    # ── NotificationHub / HistoryBufferCoordinator ───────────────────────────────────────────
    ("NH1", "error notification plays the info blip", A + "NotificationHub.cs",
     "_audioRouter.PlayEarcon(FeedbackType.Error);",
     "_audioRouter.PlayEarcon(FeedbackType.Info);",
     "an error sounds like routine information"),
    ("H01", "history exhaustion never reset", A + "HistoryBufferCoordinator.cs",
     "                    _historyExhausted = false;\n",
     "",
     "after one 'no more history', backfill is dead for the session"),
    ("H02", "'No more history' never said", A + "HistoryBufferCoordinator.cs",
     "if (addedCount > 0)",
     "if (addedCount >= 0)",
     "walking left at the start is silent forever"),
    ("H03", "a failed history load is not reported", A + "HistoryBufferCoordinator.cs",
     "                _errorCoordinator.ReportError(\n                    $\"History load failed: {ex.Message}\",",
     "                _ = (\n                    $\"History load failed: {ex.Message}\",",
     "history load errors are silent"),
    ("H04", "fetch flag never cleared", A + "HistoryBufferCoordinator.cs",
     "                    _isFetching = false;\n",
     "",
     "only the first backfill of a session ever runs"),

    # ── FeedbackRouters priority ─────────────────────────────────────────────────────────────
    ("F01", "every message takes the in-flight slot", A + "FeedbackRouters.cs",
     "if (priority >= _inFlightPriority || now >= _inFlightUntilUtc)",
     "if (true)",
     "the SECOND arrow press cuts an order rejection off"),
    ("F02", "every message protected for the 4 s cap", A + "FeedbackRouters.cs",
     "if (estimated > MaxProtectedSpeech) estimated = MaxProtectedSpeech;",
     "if (estimated < MaxProtectedSpeech) estimated = MaxProtectedSpeech;",
     "a short alert blocks arrow-key interruption for four seconds"),

    # ── GlobalErrorCoordinator ───────────────────────────────────────────────────────────────
    ("G01", "a critical error loses 'CRITICAL'", A + "GlobalErrorCoordinator.cs",
     ": ev.Severity >= ErrorSeverity.Critical",
     ": ev.Severity > ErrorSeverity.Critical",
     "a critical failure sounds like any other"),
    ("G02", "High errors lose the 'Error:' prefix", A + "GlobalErrorCoordinator.cs",
     "string prefix = (severity >= ErrorSeverity.High) ? \"Error: \" : \"\";",
     "string prefix = (severity > ErrorSeverity.High) ? \"Error: \" : \"\";",
     "a High error is spoken as a bare sentence"),
    ("G03", "High app errors no longer interrupt", A + "GlobalErrorCoordinator.cs",
     "            bool interrupt = ev.Severity >= ErrorSeverity.High;\n            _eventBus.Publish(new FeedbackRequestEvent(FeedbackType.Error, speechText",
     "            bool interrupt = ev.Severity > ErrorSeverity.High;\n            _eventBus.Publish(new FeedbackRequestEvent(FeedbackType.Error, speechText",
     "a High provider error queues behind chart speech"),

    # ── EarconService ────────────────────────────────────────────────────────────────────────
    ("E01", "buy and sell fill motifs swapped", A + "EarconService.cs",
     "            if (side == OrderSide.Buy)\n            {\n                // Two staccato",
     "            if (side != OrderSide.Buy)\n            {\n                // Two staccato",
     "a buy fill sounds like a sell"),
    ("E02", "stop hit plays the take-profit arpeggio", A + "EarconService.cs",
     "            _sonificationManager.PlayNote(220, 0.18, \"square\", 0.16f, 0f, force: true);      // A3\n            _sonificationManager.PlayNote(185, 0.18, \"square\", 0.16f, 0f, 190, force: true); // F#3\n            _sonificationManager.PlayNote(147, 0.40, \"square\", 0.14f, 0f, 380, force: true); // D3 sustained\n",
     "            _sonificationManager.PlayNote(523,  0.10, \"sine\", 0.12f, 0f, force: true);\n            _sonificationManager.PlayNote(659,  0.10, \"sine\", 0.12f, 0f, 110, force: true);\n            _sonificationManager.PlayNote(784,  0.10, \"sine\", 0.12f, 0f, 220, force: true);\n            _sonificationManager.PlayNote(1046, 0.40, \"sine\", 0.13f, 0f, 330, force: true);\n",
     "a stop loss sounds like a win"),
    ("E03", "order earcons die with the master earcon mute", A + "EarconService.cs",
     "MasterEarconsAudible() || !(_appSettings?.MuteIncludesOrderEvents ?? false);",
     "MasterEarconsAudible() && !(_appSettings?.MuteIncludesOrderEvents ?? false);",
     "Shift+F3 silences the sound of a fill the user never opted out of"),
    ("E04", "break-through alert earcon obeys the chart-earcon mute", A + "EarconService.cs",
     "if (!breakThroughMutes && !ChartEarconsAudible()) return;",
     "if (!ChartEarconsAudible()) return;",
     "a break-through alert is silent with earcons muted"),

    # ── SpeechTimeFormatter / Profile ────────────────────────────────────────────────────────
    ("S01", "a daily bar's close stamped with a clock time", A + "SpeechTimeFormatter.cs",
     "=> barSeconds < SecondsPerDay ? FormatTime(stamp) : FormatLongDate(stamp);",
     "=> barSeconds <= SecondsPerDay ? FormatTime(stamp) : FormatLongDate(stamp);",
     "every daily bar closes 'at 00:00'"),
    ("S02", "an intraday range names one date twice", A + "SpeechTimeFormatter.cs",
     "return ToDisplay(start).Date == ToDisplay(end).Date",
     "return ToDisplay(start).Date != ToDisplay(end).Date",
     "'September 5 2026 14:00 to September 5 2026 15:00' / a cross-day range loses its end date"),
    ("P01", "value-area high and low named backwards", A + "ProfileBinClassifier.cs",
     "                    return ProfileNodeType.VAH;\n                if (bin.IsValueArea && Math.Abs(bin.PriceLow - valPrice) < 1e-9)\n                    return ProfileNodeType.VAL;",
     "                    return ProfileNodeType.VAL;\n                if (bin.IsValueArea && Math.Abs(bin.PriceLow - valPrice) < 1e-9)\n                    return ProfileNodeType.VAH;",
     "the top of the value area is called its low"),
    ("P02", "value-area high takes the LOWEST bin", A + "ProfileLevels.cs",
     "if (vah == null || bin.PriceMid > vah) vah = bin.PriceMid;",
     "if (vah == null || bin.PriceMid < vah) vah = bin.PriceMid;",
     "'value area 100 to 100' — the range collapses"),

    # ── DrawingInteractionManager ────────────────────────────────────────────────────────────
    ("D01", "the 3-point prompt names the wrong next point", A + "DrawingInteractionManager.cs",
     "+ $\"Navigate to the {AnchorName(_pendingDrawingType, 2)} and press the shortcut again.\"));",
     "+ $\"Navigate to the {AnchorName(_pendingDrawingType, 1)} and press the shortcut again.\"));",
     "R/R asks for the stop loss again after the stop was set"),
    ("D02", "completion names the wrong point", A + "DrawingInteractionManager.cs",
     "string lastPoint = AnchorName(placedType, _anchorDate2 == null ? 1 : 2);",
     "string lastPoint = AnchorName(placedType, _anchorDate2 == null ? 0 : 1);",
     "'trend line placed, first point at …' for the second point"),
    ("D03", "range summary direction inverted", A + "DrawingInteractionManager.cs",
     "string dir = change >= 0 ? \"up\" : \"down\";",
     "string dir = change >= 0 ? \"down\" : \"up\";",
     "a rally is described as a fall"),
    ("D04", "risk/reward ratio never spoken", A + "DrawingInteractionManager.cs",
     "DrawingType.RiskReward when drawing.RiskRewardRatio > 0",
     "DrawingType.RiskReward when drawing.RiskRewardRatio < 0",
     "the tool's one answer is silent"),
    ("D05", "a zero-length trend line accepted", A + "DrawingInteractionManager.cs",
     "if (needsDifferentBar && date == _anchorDate1)",
     "if (false && needsDifferentBar && date == _anchorDate1)",
     "both points on one bar: an invisible line placed silently"),
    ("D06", "Escape cancels a drawing silently", A + "DrawingInteractionManager.cs",
     "            _eventBus.Publish(new AnnouncementEvent($\"{label} cancelled.\"));\n",
     "",
     "Escape is silent"),

    # ── Dot Pad ──────────────────────────────────────────────────────────────────────────────
    ("DP1", "hardware pan keys reversed", A + "Dotpad/DotpadTactileDriver.cs",
     "                DotPadKeyCode.PanningLeft  => TactileKey.PanLeft,\n                DotPadKeyCode.PanningRight => TactileKey.PanRight,",
     "                DotPadKeyCode.PanningLeft  => TactileKey.PanRight,\n                DotPadKeyCode.PanningRight => TactileKey.PanLeft,",
     "the Dot Pad's left pan key pans right"),
    ("DP2", "unplug leaves IsConnected true", A + "Dotpad/DotpadTactileDriver.cs",
     "                    IsConnected = false;\n                    _deviceHandle = IntPtr.Zero;\n                    _logger.LogInformation(\"Dot Pad disconnected.\");",
     "                    _deviceHandle = IntPtr.Zero;\n                    _logger.LogInformation(\"Dot Pad disconnected.\");",
     "no reconnect after unplugging"),
    ("T01", "F4 never turns braille on", A + "TactileCanvasCoordinator.cs",
     "bool enable = !_brailleEnabled;",
     "bool enable = _brailleEnabled;",
     "F4 repeats the current state"),
    ("T02", "graphic keeps redrawing while paused", A + "TactileCanvasCoordinator.cs",
     "            if (_isPaused) return; // F4 pause",
     "            // F4 pause",
     "pins keep moving under the user's fingers"),

    # ── Analysis: candles, indicator context, bar detail ─────────────────────────────────────
    ("SC1", "dragonfly and gravestone doji swapped", A + "SdkCandlePatternAnalyzer.cs",
     "if (lowerPct > 40 && upperPct < 8) dojiType = SdkCT.DragonflyDoji;\n                else if (upperPct > 40 && lowerPct < 8) dojiType = SdkCT.GravestoneDoji;",
     "if (lowerPct > 40 && upperPct < 8) dojiType = SdkCT.GravestoneDoji;\n                else if (upperPct > 40 && lowerPct < 8) dojiType = SdkCT.DragonflyDoji;",
     "a bullish doji is called bearish"),
    ("I01", "a bearish crossover reported as bullish", A + "IndicatorContextAnalyzer.cs",
     "if (aPrev > bPrev && aNow <= bNow) return CrossoverStatus.BearishCrossover;",
     "if (aPrev > bPrev && aNow <= bNow) return CrossoverStatus.BullishCrossover;",
     "a bear cross is narrated as bullish"),
    ("I02", "a falling trend reported as rising", A + "IndicatorContextAnalyzer.cs",
     "if (allFalling) return (TrendDirection.Falling, window.Count - 1);",
     "if (allFalling) return (TrendDirection.Rising, window.Count - 1);",
     "TrendChange alerts never fire on a turn down"),
    ("B01", "detail key's 'most recent formation' ignores knowability", A + "BarDetailService.cs",
     ".Where(p => p.ResolvesAt < idx && p.KnownAtIndex <= idx)",
     ".Where(p => p.ResolvesAt < idx)",
     "the detail key could name a formation not yet knowable"),

    # ── Headless (browser closed) ────────────────────────────────────────────────────────────
    ("HC1", "re-seed after a gap keeps the pre-gap values", A + "HeadlessChart.cs",
     "                _lastValues.Clear();\n",
     "",
     "false background crosses after the laptop sleeps"),
    ("HC2", "trim does not shift the scanner's indices", A + "HeadlessChart.cs",
     "            _scanner.ShiftIndices(drop);\n",
     "",
     "after a trim the background narrator re-speaks or skips signals"),
    ("HF1", "parameter edits do not change the chart signature", A + "HeadlessChartFactory.cs",
     "                    foreach (var p in s.Parameters.OrderBy(p => p.Key, StringComparer.Ordinal))\n                        parts.Add($\"  p:{p.Key}={p.Value.ToString(\"R\", System.Globalization.CultureInfo.InvariantCulture)}\");\n",
     "",
     "editing EMA 20→50 keeps narrating EMA 20 with the browser closed"),

    # ── AutoNarrationService ─────────────────────────────────────────────────────────────────
    ("AN1", "intra-bar scan includes the forming bar", A + "AutoNarrationService.cs",
     "int closedBound = isNewBar ? scanIndex : currentCount - 2;",
     "int closedBound = isNewBar ? scanIndex : currentCount - 1;",
     "unstable live-bar values are narrated as signals"),
    ("AN2", "the first redraw is treated as a bar close", A + "AutoNarrationService.cs",
     "bool isNewBar = currentCount > _lastDataCount && _lastDataCount > 0;",
     "bool isNewBar = currentCount > _lastDataCount;",
     "the first scan after load narrates as if a bar closed"),
    ("AN3", "the narrator's F2 gate deleted", A + "AutoNarrationService.cs",
     "            if (!state.IsSpeechEnabled) return null;\n",
     "",
     "narration scanned (and its memory spent) while F2 is on"),

    # ── TablistNavigator ─────────────────────────────────────────────────────────────────────
    ("TL1", "Left on the first tab does not wrap", A + "TablistNavigator.cs",
     "else if (key == backward) target = (at - 1 + count) % count;",
     "else if (key == backward) target = Math.Max(at - 1, 0);",
     "Left on the first Settings tab is a dead key"),
]

# ── Selection ────────────────────────────────────────────────────────────────────────────────
# The list above was drafted wide (82); the campaign runs the 50 below, per the brief's 35–50.
# Dropped and why:
#   C16, NH1 — NotificationHub.NotifyError/NotifyAlert have NO production caller (only
#              IndicatorOrchestrator → NotifyInfo), so mutants there are on dead code.
#   C13, C14, A08, A10, A11, A12, A13, A14, N07, N08, PN1, V02, R02, H03, H04, G02, G03, E03,
#   E04, S02, P02, D04, D05, D06, DP2, T02, I02, B01, HC2, TL1 — lower user harm than the kept
#   sibling in the same file/behaviour, or (B01) likely equivalent by the KnownAtIndex <=
#   ResolvesAt invariant. Not run; not counted.
SELECTED = [
    "C01", "C02", "C03", "C04", "C05", "C06", "C07", "C08", "C09", "C10", "C11", "C12", "C15",
    "A01", "A02", "A03", "A04", "A05", "A06", "A07", "A09",
    "N01", "N02", "N03", "N04", "N05", "N06",
    "V01", "R01", "H01", "H02", "F01", "F02", "G01",
    "E01", "E02", "S01", "P01", "D01", "D02", "D03", "DP1", "T01",
    "SC1", "I01", "HC1", "HF1", "AN1", "AN2", "AN3",
]
ALL_MUTANTS = MUTANTS
MUTANTS = [m for m in ALL_MUTANTS if m[0] in SELECTED]
assert len(MUTANTS) == len(SELECTED) == 50, (len(MUTANTS), len(SELECTED))
